### ISSUE TITLE
Implement Typing Sounds

### ISSUE THREAD

**Issue by NavneetNayak** [acmpesuecc/py-typer#1]
Add typing sounds every time the user presses a key, there should be no sound if the user presses the wrong letter. Use whatever library you like to do so. The added sound should cause no lag / performance issues.
Propose and add a way for users to choose among multiple different sounds.

Points will be assigned based on proposal and implementation.

**Comment by DeviousDrops** [comment]
can u assign this to me?

**Comment by jishnu-sivakumar** [comment]
can u assign this to me?

**Comment by NavneetNayak** [comment]
@DeviousDrops  do you still want to work on this?

**Comment by DeviousDrops** [comment]
yes

**Comment by NavneetNayak** [comment]
!assign @DeviousDrops

**Comment by mahika34** [comment]
can i be assigned?

**Comment by ashyune** [comment]
can I be assigned?

**Comment by Andy34G7** [comment]
Can I be assigned to this issue?

**Comment by NavneetNayak** [comment]
@mahika34 do you want to work on this?

**Comment by DHANUVARSHA04** [comment]
Can I work on this ?

**Comment by NavneetNayak** [comment]
@ashyune do you want to work on this

**Comment by NavneetNayak** [comment]
@Andy34G7 do you want to work on this?

**Comment by NavneetNayak** [comment]
@DHANUVARSHA04 do you still want to work on this?

**Comment by DHANUVARSHA04** [comment]
Yes

**Comment by ashyune** [comment]
> @ashyune do you want to work on this

Yes

**Comment by Andy34G7** [comment]
> @Andy34G7 do you want to work on this?

Yes

**Comment by mahika34** [comment]
i want to work on it

**Comment by DHANUVARSHA04** [comment]
Going for dinner please extend time

**Comment by NavneetNayak** [comment]
!asign @DHANUVARSHA04

**Comment by NavneetNayak** [comment]
@DHANUVARSHA04 you are assigned to some other issue please withdraw from it using !withdraw

**Comment by PerepaMoorty** [comment]
I could implement the Typing sounds, Can I get this assignment?

**Comment by stealthwhizz** [comment]
can u assign me this?

**Comment by NavneetNayak** [comment]
@mahika34 @ashyune @PerepaMoorty @stealthwhizz  pls message if you want to work on it, I will assign the first person to respond

**Comment by PerepaMoorty** [comment]
I would like to work on this

**Comment by stealthwhizz** [comment]
> @mahika34 @ashyune @PerepaMoorty @stealthwhizz pls message if you want to work on it, I will assign the first person to respond

yes sure

**Comment by Greninja34** [comment]
Hey there! Could I be assigned to this @NavneetNayak

**Comment by NavneetNayak** [comment]
!assign @PerepaMoorty

**Comment by NavneetNayak** [comment]
!deassign

**Comment by NavneetNayak** [comment]
!assign @PerepaMoorty

**Comment by PerepaMoorty** [comment]
How long do I get for this

**Comment by NavneetNayak** [comment]
45 mins after which based on progress it may be extended

**Comment by PerepaMoorty** [comment]
I have made a pull request, Please do review it

**Comment by Anyaaa-2** [comment]
can i be assigned

**Comment by NavneetNayak** [comment]
!deassign @PerepaMoorty

**Comment by NavneetNayak** [comment]
!assign @PerepaMoorty

**Comment by NavneetNayak** [comment]
Done in #7

**Comment by NavneetNayak** [comment]
!deassign @PerepaMoorty
