### ISSUE TITLE
Feature: Zen Mode

### ISSUE THREAD

**Issue by NavneetNayak** [acmpesuecc/py-typer#2]
Implement another mode called difficult mode `Zen mode` which takes inspiration from `monkeytype.com`'s zen mode, in much the same way allow the user to infinitely type words with no limit and calculate the wpm at the end. Press `shift + enter` 

https://github.com/user-attachments/assets/b892d201-6019-4bbf-88d9-7314033c16e0

**Comment by mrwhats-it** [comment]
can i be assigned this issue?

**Comment by jishnu-sivakumar** [comment]
can i try to solve this issue?

**Comment by Nishanth2465** [comment]
can i be assigned

**Comment by namrataaravinda** [comment]
can i get this issue assigned please?

**Comment by NavneetNayak** [comment]
@Mathew-K-Alexander  do you still want to work on this issue?

**Comment by namrataaravinda** [comment]
yes!

**Comment by NavneetNayak** [comment]
@Eggz2258 do you still want to work on this issue

**Comment by NavneetNayak** [comment]
@Nishanth2465 do you still want to work on this issue

**Comment by NavneetNayak** [comment]
@namrataaravinda do you still want to work on this

**Comment by codespiderr** [comment]
can i work on this issue?

**Comment by NavneetNayak** [comment]
!assign @codespiderr

**Comment by namrataaravinda** [comment]
> @namrataaravinda do you still want to work on this

yes please!

**Comment by codespiderr** [comment]
@NavneetNayak I am going to dinner please have my time extended

**Comment by NavneetNayak** [comment]
@codespiderr please make pr with current progress depending on progress I will extend

**Comment by NavneetNayak** [comment]
!deassign @codespiderr

**Comment by NavneetNayak** [comment]
@codespiderr please req for issue if you want to work on it again

**Comment by Nightwing000** [comment]
Can i be assigned?

**Comment by NavneetNayak** [comment]
!assign @Nightwing000

**Comment by NavneetNayak** [comment]
!assign @Nightwing000

**Comment by NavneetNayak** [comment]
@Nightwing000  you are assigned to some other issue please deassign from that issue

**Comment by Greninja34** [comment]
Hey there! Could I be assigned to this? @NavneetNayak

**Comment by NavneetNayak** [comment]
!assign @Gekkouga77

**Comment by Greninja34** [comment]
how much time is provided?

**Comment by NavneetNayak** [comment]
!assign @Gekkouga

**Comment by NavneetNayak** [comment]
!assign @Gekkouga77

**Comment by NavneetNayak** [comment]
@Gekkouga77 you are not assigned this issue due to some problem, but you can work on this

**Comment by Greninja34** [comment]
okay

**Comment by NavneetNayak** [comment]
@Gekkouga77 please make a pr to show progress if you want an extension

**Comment by NavneetNayak** [comment]
!deassign @Gekkouga77

**Comment by Greninja34** [comment]
hey there! just saw your comment. My terminal has crashed. I would like an extension if possible. I will be making pr in a minute or two.

**Comment by NavneetNayak** [comment]
!assign @Gekkouga77

**Comment by Manvith-M-Nayak** [comment]
Can I be assigned please?

**Comment by NavneetNayak** [comment]
@Manvith-M-Nayak @Gekkouga77 has been assigned this issue for now, please wait another 30 mins if there is no extension Ill assign the issue to you

**Comment by NavneetNayak** [comment]
!deassign @Gekkouga77

**Comment by NavneetNayak** [comment]
!assign @Gekkouga77

**Comment by Greninja34** [comment]
could I get an extension?

**Comment by NavneetNayak** [comment]
@Gekkouga77 I can give you an extension of 15 mins after which ill have to assign other people if they want the issue

**Comment by NavneetNayak** [comment]
!assign @Gekkouga77 15

**Comment by Greninja34** [comment]
okay

**Comment by NavneetNayak** [comment]
@Gekkouga77  please update

**Comment by Greninja34** [comment]
my terminal crashed
i relaunching it 
one sec pls

**Comment by NavneetNayak** [comment]
!deassign @Gekkouga77

**Comment by NavneetNayak** [comment]
!assign @Gekkouga77

**Comment by Omkar-Patil-08-05** [comment]
can you assign me this

**Comment by NavneetNayak** [comment]
@Omkar-Patil-08-05 do you still want to work on this

**Comment by Omkar-Patil-08-05** [comment]
no

**Comment by NavneetNayak** [comment]
!deassign @Gekkouga77

**Comment by Manvith-M-Nayak** [comment]
Assign me

**Comment by jishnu-sivakumar** [comment]
can i give it a try

**Comment by AutisticCoder-9000** [comment]
Can I be assigned on this issue?

**Comment by Sabique-Islam** [comment]
please assign

**Comment by NavneetNayak** [comment]
!assign @Manvith-M-Nayak

**Comment by NavneetNayak** [comment]
@Manvith-M-Nayak  you are assigned to some other issue !withdraw from it only then I can assign you this

**Comment by jishnu-sivakumar** [comment]
may i ??

**Comment by NavneetNayak** [comment]
solved in #8
