### ISSUE TITLE
Fix Screen Glitch!?

### ISSUE THREAD

**Issue by NavneetNayak** [acmpesuecc/py-typer#3]
If you check `demo.gif` in the `docs/` folder you will see a screen glitch when the user finishes the typing test, this is likely caused by the following function. Clearing the screen.
```
def main_menu(self):
    self.clear()
```
This may or may not be the root cause of the bug, but is a good starting point for debugging. 

More points than the specified amount may be given based on how difficult it turns out to fix the bug.

**Comment by krish06m** [comment]
Please assign me this issue

**Comment by RisuKumari11** [comment]
can i get assigned this

**Comment by NavneetNayak** [comment]
@krish06m do you still want to work on this?

**Comment by krish06m** [comment]
yes

**Comment by NavneetNayak** [comment]
!assign @krish06m

**Comment by Prabhanjan3247** [comment]
Please assign me this issue

**Comment by krish06m** [comment]
im going for dinner

**Comment by NavneetNayak** [comment]
@krish06m please make a pr with your current progress I will extend based on that

**Comment by krish06m** [comment]
im back

**Comment by krish06m** [comment]
im still trying to figure it out

**Comment by NavneetNayak** [comment]
since no one else has requested for this issue Ill extend your time, but next time open a pr with your progress

**Comment by NavneetNayak** [comment]
!extend @krish06m

**Comment by NavneetNayak** [comment]
!extend

**Comment by krish06m** [comment]
i wasnt able to solve the issue @NavneetNayak

**Comment by NavneetNayak** [comment]
@krish06m if you wish to not work on this issue anymore please withdraw using !withdraw

**Comment by krish06m** [comment]
can you give me another 10mins

**Comment by Son-0f-Anton** [comment]
can i be assigned this

**Comment by krish06m** [comment]
!withdraw

**Comment by NavneetNayak** [comment]
!assign @Anagha-Rao-53

**Comment by NavneetNayak** [comment]
!assign @Anagha-Rao-53

**Comment by NavneetNayak** [comment]
@Anagha-Rao-53 you are assigned to some other issue please deassign from that issue

**Comment by Greninja34** [comment]
Hey there! Could I be assigned to this? @NavneetNayak

**Comment by NavneetNayak** [comment]
!assign @Anagha-Rao-53 60

**Comment by Son-0f-Anton** [comment]
ok will deassign

**Comment by Son-0f-Anton** [comment]
not assigned to anything

**Comment by NavneetNayak** [comment]
!assign @Anagha-Rao-53

**Comment by Am3li1** [comment]
can i get assigned to this?

**Comment by NavneetNayak** [comment]
!assign @Anagha-Rao-53

**Comment by NavneetNayak** [comment]
@Am3li1 do you still want to work on this?

**Comment by NavneetNayak** [comment]
@Anagha-Rao-53 please create pr to show progress if you want an extension

**Comment by Ferrari2025** [comment]
can you please assign this issue to me

**Comment by NavneetNayak** [comment]
!deassign @Anagha-Rao-53

**Comment by NavneetNayak** [comment]
!assign @Ferrari2025

**Comment by Aditya-C-S** [comment]
can u assign me this , because no one else has been assigned

**Comment by NavneetNayak** [comment]
!assign @Aditya-C-S

**Comment by Aditya-C-S** [comment]
@NavneetNayak i fixed the bug , now i am going to send a pull request

**Comment by NavneetNayak** [comment]
@Aditya-C-S you haven't made any pr

**Comment by Aditya-C-S** [comment]
did it just now

**Comment by NavneetNayak** [comment]
!deassign @Aditya-C-S

**Comment by RAKSHITHA9990** [comment]
can u assign me this?

**Comment by NavneetNayak** [comment]
solved in #9
