### ISSUE TITLE
Feature: Themes

### ISSUE THREAD

**Issue by NavneetNayak** [acmpesuecc/py-typer#4]
Currently the colors of all UI elements are hard coded, implement a theming system. Propose and implement a dynamic theming system. Where the user should easily be able to switch between themes and even create and import custom themes.

Points will be assigned based on the proposal and implementation.

**Comment by AyushChakraborty** [comment]
Kindly assign this issue to me

**Comment by Sabique-Islam** [comment]
May I have this?

**Comment by SamridhiShreyaa** [comment]
can i be assigned?

**Comment by NavneetNayak** [comment]
@AyushChakraborty do you still want to work on this?

**Comment by AyushChakraborty** [comment]
@NavneetNayak yes

**Comment by NavneetNayak** [comment]
!assign @AyushChakraborty

**Comment by NavneetNayak** [comment]
@AyushChakraborty go ahead

**Comment by AyushChakraborty** [comment]
yup

**Comment by ayaanGH06** [comment]
can i get assigned this issue

**Comment by NavneetNayak** [comment]
@Sabique-Islam  do you still want to work on this?

**Comment by NavneetNayak** [comment]
@SamridhiShreyaa do you want to work on this

**Comment by Gunika-Goel** [comment]
can i be assigned please?

**Comment by AyushChakraborty** [comment]
I am creating a PR for it now @NavneetNayak

**Comment by AyushChakraborty** [comment]
Yo Navneet Anupam Here- Since there is no assignee you make your decision whether or not to accept or reject.

**Comment by NavneetNayak** [comment]
!assign @AyushChakraborty

**Comment by NavneetNayak** [comment]
!assign @AyushChakraborty

**Comment by NavneetNayak** [comment]
@AyushChakraborty please share your progress on the pr will extend based on that

**Comment by AyushChakraborty** [comment]
@NavneetNayak pls chk the PR now, its updated, added more features

**Comment by NavneetNayak** [comment]
!deassign @AyushChakraborty

**Comment by NavneetNayak** [comment]
!assign @AyushChakraborty

**Comment by NavneetNayak** [comment]
!deassign @AyushChakraborty

**Comment by NavneetNayak** [comment]
!assign @AyushChakraborty

**Comment by NavneetNayak** [comment]
done in #5

**Comment by NavneetNayak** [comment]
!deassign @AyushChakraborty
